// MobileGoldArmy_NEW/app/settings.tsx
import React, { useState, useEffect } from 'react';
import { View, Text, TouchableOpacity, ScrollView, ActivityIndicator, Alert, StyleSheet, Platform, Animated } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { SafeAreaView } from 'react-native-safe-area-context';
import { StatusBar } from 'expo-status-bar';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useAuth } from '../src/hooks/useAuth';
import { profileService, UserProfile } from '../src/services/profileService';

const tiers = [
  {
    name: 'Gratuit',
    id: 'tier-free',
    price: '0€',
    description: 'Pour débuter votre conquête du marché.',
    features: [
      '2 recherches Sniper / jour',
      '2 audits de CV (Mentor IA)',
      '1 entretien RH vocal',
      '5 relances automatiques',
      '3 adaptations de CV par IA',
      'Accès communautaire',
    ],
    unavailable: [
      'Usage Headhunter',
      'Carnet d\'adresses privé',
      'Portfolio personnalisé'
    ],
    buttonText: 'Plan Actuel',
    highlighted: false,
    icon: 'shield-checkmark',
    gradientColors: ['#1E293B', '#0F172A'],
    iconColor: '#94A3B8'
  },
  {
    name: 'Essentiel',
    id: 'tier-essential',
    price: '9.99€',
    description: 'Le choix des vainqueurs (Conseillé).',
    features: [
      '25 recherches Sniper / mois',
      '10 audits de CV ATS',
      '10 entretiens RH vocaux',
      '10 usages Headhunter',
      '25 places au carnet d\'adresses',
      'Relances illimitées',
      'Adaptations CV illimitées',
    ],
    unavailable: [],
    buttonText: 'Choisir Essentiel',
    highlighted: true,
    icon: 'star',
    gradientColors: ['rgba(245, 158, 11, 0.1)', 'rgba(245, 158, 11, 0.02)'], 
    iconColor: '#F59E0B'
  },
  {
    name: 'Pro',
    id: 'tier-pro',
    price: '19.99€',
    description: 'Puissance de feu maximale pour l\'élite.',
    features: [
      'Recherches Sniper illimitées',
      '20 audits de CV approfondis',
      '15 entretiens RH IA',
      'Headhunter illimité (Automation)',
      'Carnet d\'adresses illimité',
      'Portfolio personnalisé IA',
      'Support Prioritaire 24/7',
    ],
    unavailable: [],
    buttonText: 'Devenir Pro',
    highlighted: false,
    icon: 'rocket',
    gradientColors: ['rgba(99, 102, 241, 0.15)', 'rgba(99, 102, 241, 0.05)'],
    iconColor: '#818CF8'
  }
];

export default function SettingsScreen() {
  const router = useRouter();
  const { user } = useAuth();
  const [isSubscribing, setIsSubscribing] = useState<string | null>(null);
  const [profile, setProfile] = useState<UserProfile | null>(null);
  const [loading, setLoading] = useState(true);

  React.useEffect(() => {
    profileService.getProfile()
      .then(data => setProfile(data))
      .catch(err => console.log('Err fetching profile', err))
      .finally(() => setLoading(false));
  }, []);

  // Fallback to FREE if user tier is empty
  const userTier = profile?.subscription_tier || 'FREE';
  const userName = profile?.full_name || 'Utilisateur';

  const handleSubscribe = async (tierId: string) => {
    if (isSubscribing) return;
    
    const tierMap: Record<string, string> = {
      'tier-free': 'FREE',
      'tier-essential': 'ESSENTIAL',
      'tier-pro': 'PRO'
    };
    const tier = tierMap[tierId];
    
    if (tier === 'FREE') {
       router.push('/(tabs)/home');
       return;
    }
    
    if (tier === userTier) {
      Alert.alert("Info", "Vous êtes déjà sur ce forfait.");
      return;
    }

    setIsSubscribing(tierId);
    try {
      // Fake delay to simulate backend request
      await new Promise(resolve => setTimeout(resolve, 1500));
      Alert.alert("Succès", "Redirection vers la page de paiement Stripe (Simulation).");
    } catch (err) {
      Alert.alert("Erreur", "Erreur de connexion au service de paiement.");
    } finally {
      setIsSubscribing(null);
    }
  };

  const handleAlertChange = (title: string) => {
    Alert.alert(title, "Cette fonctionnalité sera bientôt connectée au backend Gemini 3.1.", [{ text: "OK", style: "default" }]);
  };

  const handleDeleteAccount = () => {
    Alert.alert(
      "Suppression du compte", 
      "Attention, cette action est irréversible. Toutes vos données seront effacées.", 
      [
        { text: "Annuler", style: "cancel" },
        { text: "Confirmer la suppression", style: "destructive", onPress: () => Alert.alert("Succès", "Demande de suppression envoyée au support.") }
      ]
    );
  };

  const getTiers = () => {
    return tiers.map(t => {
      let isActive = (t.id === 'tier-free' && userTier === 'FREE') || 
                     (t.id === 'tier-essential' && userTier === 'ESSENTIAL') ||
                     (t.id === 'tier-pro' && userTier === 'PRO');
      
      let buttonText = isActive ? 'Plan Actuel' : t.buttonText;
      let tierName = t.name;

      if (t.id === 'tier-pro' && userTier === 'ADMIN') {
        isActive = true;
        buttonText = 'Plan Admin GoldArmy';
        tierName = 'Admin';
      }

      return {
        ...t,
        name: tierName,
        buttonText,
        highlighted: t.id === 'tier-essential' || isActive,
        isActive
      };
    });
  };

  return (
    <SafeAreaView style={styles.root}>
      <StatusBar style="light" />
      <View style={styles.header}>
        <TouchableOpacity style={styles.backButton} onPress={() => router.back()}>
          <Ionicons name="arrow-back" size={24} color="#94A3B8" />
        </TouchableOpacity>
        <View style={styles.headerTitleContainer}>
          <Text style={styles.title}>Paramètres <Text style={styles.titleHighlight}>&</Text> Abonnements</Text>
          <Text style={styles.subtitle}>Optimisez votre arsenal et gérez vos privilèges GoldArmy.</Text>
        </View>
      </View>

      <ScrollView style={styles.scroll} contentContainerStyle={styles.content}>
        
        {/* Pricing Grid */}
        <View style={styles.pricingGrid}>
          {getTiers().map(tier => (
            <View 
              key={tier.id} 
              style={[
                styles.tierCard, 
                tier.highlighted && styles.tierCardHighlighted
              ]}
            >
              {tier.highlighted && (
                <LinearGradient
                   colors={['rgba(245, 158, 11, 0.15)', 'transparent']}
                   style={[StyleSheet.absoluteFillObject, { borderRadius: 24 }]}
                   start={{ x: 0.5, y: 0 }}
                   end={{ x: 0.5, y: 1 }}
                />
              )}
              {tier.highlighted && (
                <View style={styles.popularBadge}>
                  <LinearGradient
                    colors={['#F5D061', '#F59E0B']}
                    start={{ x: 0, y: 0 }}
                    end={{ x: 1, y: 0 }}
                    style={styles.popularBadgeGradient}
                  >
                    <Text style={styles.popularBadgeText}>LE PLUS POPULAIRE</Text>
                  </LinearGradient>
                </View>
              )}
              
              <View style={styles.tierHeader}>
                <View style={[styles.iconContainer, { backgroundColor: tier.gradientColors[0] }]}>
                  <Ionicons name={tier.icon as any} size={26} color={tier.iconColor} />
                </View>
                <Text style={styles.tierName}>{tier.name}</Text>
                <View style={styles.priceRow}>
                  <Text style={styles.tierPrice}>{tier.price}</Text>
                  <Text style={styles.tierPriceSub}>/ mois</Text>
                </View>
                <Text style={styles.tierDesc}>{tier.description}</Text>
              </View>

              <View style={styles.featuresContainer}>
                {tier.features.map((feat, idx) => (
                  <View key={`feat-${idx}`} style={styles.featureRow}>
                    <View style={styles.checkIconWrapper}>
                      <Ionicons name="checkmark" size={14} color="#10B981" />
                    </View>
                    <Text style={styles.featureText}>{feat}</Text>
                  </View>
                ))}
                {tier.unavailable.map((unfeat, idx) => (
                  <View key={`unfeat-${idx}`} style={[styles.featureRow, { opacity: 0.4 }]}>
                    <View style={styles.crossIconWrapper}>
                      <View style={styles.horizontalLine} />
                    </View>
                    <Text style={[styles.featureText, { textDecorationLine: 'line-through' }]}>{unfeat}</Text>
                  </View>
                ))}
              </View>

              <TouchableOpacity 
                style={[styles.subscribeBtnWrapper, isSubscribing === tier.id && { opacity: 0.7 }]}
                onPress={() => handleSubscribe(tier.id)}
                disabled={isSubscribing !== null}
                activeOpacity={0.8}
              >
                <LinearGradient
                  colors={tier.highlighted ? ['#F5D061', '#F59E0B'] : ['#334155', '#1E293B']}
                  start={{ x: 0, y: 0 }}
                  end={{ x: 1, y: 0 }}
                  style={[styles.subscribeBtn, tier.highlighted ? styles.subscribeBtnHighlighted : styles.subscribeBtnNormal]}
                >
                  {isSubscribing === tier.id ? (
                    <ActivityIndicator color={tier.highlighted ? '#1E293B' : '#FFF'} />
                  ) : (
                    <Text style={[
                        styles.subscribeBtnText, 
                        tier.highlighted ? styles.subscribeBtnTextHighlighted : styles.subscribeBtnTextNormal
                      ]}
                    >
                      {tier.buttonText}
                    </Text>
                  )}
                </LinearGradient>
              </TouchableOpacity>
            </View>
          ))}
        </View>

        {/* Extra Settings Section */}
        <View style={styles.extraSettings}>
          {/* AI Settings */}
          <View style={styles.settingSection}>
            <View style={styles.settingSectionHeader}>
              <View style={[styles.sectionIconBg, { backgroundColor: 'rgba(99, 102, 241, 0.1)' }]}>
                <Ionicons name="sparkles" size={20} color="#6366F1" />
              </View>
              <Text style={styles.settingSectionTitle}>Préférences IA</Text>
            </View>
            
            <TouchableOpacity style={styles.settingItem} onPress={() => handleAlertChange("Précision Sniper")}>
              <View>
                <Text style={styles.settingLabel}>Précision de filtrage Sniper</Text>
                <Text style={styles.settingSubLabel}>Définit le niveau de sévérité de Gemini 3.1</Text>
              </View>
              <Text style={styles.settingValueText}>Standard (Auto)</Text>
            </TouchableOpacity>
            
            <TouchableOpacity style={styles.settingItem} onPress={() => handleAlertChange("Voix de l'entretien")}>
              <View>
                <Text style={styles.settingLabel}>Voix de l'entretien</Text>
                <Text style={styles.settingSubLabel}>Sélectionnez le profil vocal du recruteur IA</Text>
              </View>
              <Text style={styles.settingValueText}>Recruteur Standard</Text>
            </TouchableOpacity>
          </View>

          {/* Profile & Privacy */}
          <View style={styles.settingSection}>
            <View style={styles.settingSectionHeader}>
              <View style={[styles.sectionIconBg, { backgroundColor: 'rgba(16, 185, 129, 0.1)' }]}>
                <Ionicons name="people" size={20} color="#10B981" />
              </View>
              <Text style={styles.settingSectionTitle}>Profil & Confidentialité</Text>
            </View>

            <View style={styles.profileBadge}>
              <View style={styles.profileBadgeAvatar}>
                <Text style={styles.profileBadgeAvatarText}>{userName.charAt(0).toUpperCase()}</Text>
              </View>
              <View style={{ flex: 1 }}>
                <Text style={styles.profileBadgeName}>{userName}</Text>
                <Text style={styles.profileBadgeTier}>
                  {userTier === 'ADMIN' ? 'Administrateur GoldArmy' : 
                   userTier === 'PRO' ? 'Membre GoldArmy Pro' : 'Utilisateur GoldArmy'}
                </Text>
              </View>
            </View>

             <TouchableOpacity style={styles.deleteAccountBtn} onPress={handleDeleteAccount}>
                <Text style={styles.deleteAccountBtnText}>Supprimer mon compte et mes données</Text>
             </TouchableOpacity>

          </View>
        </View>

      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#0F172A', // Dark mode by default for premium feel
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'android' ? 40 : 10,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#1E293B',
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#1E293B',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  headerTitleContainer: {
    flex: 1,
  },
  title: {
    fontSize: 22,
    fontWeight: '900',
    color: '#FFF',
  },
  titleHighlight: {
    color: '#F59E0B',
  },
  subtitle: {
    fontSize: 12,
    color: '#94A3B8',
    marginTop: 2,
  },
  scroll: {
    flex: 1,
  },
  content: {
    padding: 20,
    paddingBottom: 40,
  },
  pricingGrid: {
    gap: 24,
    marginBottom: 40,
  },
  tierCard: {
    backgroundColor: '#1E293B',
    borderRadius: 32,
    padding: 24,
    borderWidth: 1,
    borderColor: '#334155',
    position: 'relative',
    overflow: 'hidden',
  },
  tierCardHighlighted: {
    borderColor: '#F59E0B',
    backgroundColor: '#1E293B',
    shadowColor: '#F59E0B',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 8,
  },
  popularBadge: {
    position: 'absolute',
    top: -1,
    alignSelf: 'center',
  },
  popularBadgeGradient: {
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
  },
  popularBadgeText: {
    fontSize: 10,
    fontWeight: '900',
    color: '#0F172A',
    letterSpacing: 1.5,
  },
  tierHeader: {
    marginBottom: 24,
    marginTop: 8,
  },
  iconContainer: {
    width: 60,
    height: 60,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    borderWidth: 1,
    borderColor: 'rgba(245, 158, 11, 0.1)',
  },
  tierName: {
    fontSize: 24,
    fontWeight: '900',
    color: '#FFF',
    marginBottom: 4,
    letterSpacing: -0.5,
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    marginBottom: 12,
  },
  tierPrice: {
    fontSize: 42,
    fontWeight: '900',
    color: '#FFF',
    letterSpacing: -1,
  },
  tierPriceSub: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#94A3B8',
    marginLeft: 6,
    textTransform: 'uppercase',
  },
  tierDesc: {
    fontSize: 14,
    color: '#94A3B8',
    lineHeight: 20,
    fontWeight: '500',
  },
  featuresContainer: {
    gap: 16,
    marginBottom: 32,
  },
  featureRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  checkIconWrapper: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.3)',
  },
  crossIconWrapper: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#334155',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#475569',
  },
  horizontalLine: {
    width: 6,
    height: 2,
    backgroundColor: '#64748B',
    borderRadius: 1,
  },
  featureText: {
    fontSize: 14,
    color: '#E2E8F0',
    flex: 1,
    fontWeight: '600',
  },
  subscribeBtnWrapper: {
    width: '100%',
    borderRadius: 20,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
  },
  subscribeBtn: {
    width: '100%',
    paddingVertical: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  subscribeBtnNormal: {
    borderWidth: 1,
    borderColor: '#475569',
  },
  subscribeBtnHighlighted: {
    // Gradient handles background
  },
  subscribeBtnText: {
    fontSize: 14,
    fontWeight: 'bold',
    textTransform: 'uppercase',
  },
  subscribeBtnTextNormal: {
    color: '#FFF',
  },
  subscribeBtnTextHighlighted: {
    color: '#0F172A',
  },
  extraSettings: {
    gap: 20,
  },
  settingSection: {
    backgroundColor: '#1E293B',
    borderRadius: 24,
    padding: 24,
    borderWidth: 1,
    borderColor: '#334155',
  },
  settingSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 20,
  },
  sectionIconBg: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingSectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFF',
  },
  settingItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  settingLabel: {
    color: '#F8FAFC',
    fontSize: 14,
    fontWeight: '600',
  },
  settingSubLabel: {
    color: '#64748B',
    fontSize: 11,
    marginTop: 2,
    maxWidth: 200,
  },
  settingValueText: {
    color: '#CBD5E1',
    fontSize: 12,
    fontWeight: 'bold',
    backgroundColor: '#334155',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
  },
  profileBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0F172A',
    padding: 15,
    borderRadius: 16,
    gap: 15,
    marginBottom: 15,
  },
  profileBadgeAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(245, 158, 11, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileBadgeAvatarText: {
    color: '#F59E0B',
    fontSize: 18,
    fontWeight: 'bold',
  },
  profileBadgeName: {
    color: '#F8FAFC',
    fontSize: 14,
    fontWeight: 'bold',
  },
  profileBadgeTier: {
    color: '#64748B',
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
    marginTop: 2,
  },
  deleteAccountBtn: {
    paddingVertical: 15,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.2)',
    borderRadius: 16,
    backgroundColor: 'rgba(239, 68, 68, 0.05)',
  },
  deleteAccountBtnText: {
    color: '#F87171',
    fontSize: 12,
    fontWeight: 'bold',
  }
});

// frontend/src/views/Settings.vue
<script setup>
import { 
  ArrowLeftIcon, 
  CheckIcon, 
  StarIcon, 
  RocketLaunchIcon, 
  SparklesIcon,
  ShieldCheckIcon,
  UserGroupIcon,
  BriefcaseIcon,
  MicrophoneIcon,
  MapIcon
} from '@heroicons/vue/24/outline'
import { authFetch } from '../utils/auth'
import { ref, onMounted, computed } from 'vue'
import { useRouter } from 'vue-router'

const router = useRouter()
const goBack = () => router.push('/dashboard')

const tiers = [
  {
    name: 'Gratuit',
    id: 'tier-free',
    price: '0€',
    description: 'Pour débuter votre conquête du marché.',
    features: [
      '2 recherches Sniper / jour',
      '2 audits de CV (Mentor IA)',
      '1 entretien RH vocal',
      '5 relances automatiques',
      '3 adaptations de CV par IA',
      'Accès communautaire',
    ],
    unavailable: [
      'Usage Headhunter',
      'Carnet d\'adresses privé',
      'Portfolio personnalisé'
    ],
    buttonText: 'Plan Actuel',
    highlighted: false,
    gradient: 'from-slate-800 to-slate-900',
    icon: ShieldCheckIcon
  },
  {
    name: 'Essentiel',
    id: 'tier-essential',
    price: '9.99€',
    description: 'Le choix des vainqueurs (Conseillé).',
    features: [
      '25 recherches Sniper / mois',
      '10 audits de CV ATS',
      '10 entretiens RH vocaux',
      '10 usages Headhunter',
      '25 places au carnet d\'adresses',
      'Relances illimitées',
      'Adaptations CV illimitées',
    ],
    buttonText: 'Choisir Essentiel',
    highlighted: true,
    gradient: 'from-amber-500/10 to-gold-500/5',
    icon: StarIcon
  },
  {
    name: 'Pro',
    id: 'tier-pro',
    price: '19.99€',
    description: 'Puissance de feu maximale pour l\'élite.',
    features: [
      'Recherches Sniper illimitées',
      '20 audits de CV approfondis',
      '15 entretiens RH IA',
      'Headhunter illimité (Automation)',
      'Carnet d\'adresses illimité',
      'Portfolio personnalisé IA',
      'Support Prioritaire 24/7',
    ],
    buttonText: 'Devenir Pro',
    highlighted: false,
    gradient: 'from-indigo-600/20 to-violet-600/10',
    icon: RocketLaunchIcon
  }
]

const userTier = ref('FREE')

const fetchProfile = async () => {
  try {
    const res = await authFetch('/api/profile')
    const json = await res.json()
    if (json.status === 'success') {
      userTier.value = json.data.subscription_tier || 'FREE'
    }
  } catch (e) {
    console.error("Failed to fetch profile", e)
  }
}

onMounted(fetchProfile)

const isSubscribing = ref(false)

const handleSubscribe = async (tierId) => {
  if (isSubscribing.value) return
  
  // Mapping frontend IDs to backend tier names
  const tierMap = {
    'tier-free': 'FREE',
    'tier-essential': 'ESSENTIAL',
    'tier-pro': 'PRO'
  }
  
  const tier = tierMap[tierId]
  if (tier === 'FREE') {
    // Already handled or just redirect to dashboard
    router.push('/dashboard')
    return
  }
  
  if (tier === userTier.value) {
    toastState.addToast("Vous êtes déjà sur ce forfait.", "info")
    return
  }

  isSubscribing.value = true
  try {
    const res = await authFetch('/api/stripe/create-checkout-session', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ tier })
    })
    const json = await res.json()
    if (json.status === 'success' && json.url) {
      window.location.href = json.url
    } else {
      toastState.addToast("Erreur lors de la création de la session Stripe.", "error")
    }
  } catch (e) {
    toastState.addToast("Erreur de connexion au service de paiement.", "error")
  } finally {
    isSubscribing.value = false
  }
}

const displayTiers = computed(() => {
  return tiers.map(t => {
    let isActive = (t.id === 'tier-free' && userTier.value === 'FREE') || 
                   (t.id === 'tier-essential' && userTier.value === 'ESSENTIAL') ||
                   (t.id === 'tier-pro' && userTier.value === 'PRO')
    
    // Branding Admin for Pro tier if user is Admin
    let buttonText = isActive ? 'Plan Actuel' : t.buttonText
    let tierName = t.name
    
    if (t.id === 'tier-pro' && userTier.value === 'ADMIN') {
        isActive = true
        buttonText = 'Plan Admin GoldArmy'
        tierName = 'Admin'
    }

    return {
      ...t,
      name: tierName,
      buttonText: buttonText,
      highlighted: t.id === 'tier-essential' || isActive
    }
  })
})
</script>

<template>
  <div class="px-4 md:px-10 py-8 max-w-[1400px] mx-auto w-full animate-fade-in-up">
    
    <!-- Top Header -->
    <div class="flex items-center justify-between border-b border-surface-800 pb-8 mb-12 mt-6">
        <div class="flex items-center gap-6">
            <button @click="goBack" class="group p-3 bg-surface-900 border border-surface-800 hover:border-gold-500/50 rounded-2xl text-slate-400 hover:text-white transition-all shadow-sm">
                <ArrowLeftIcon class="w-6 h-6 group-hover:-translate-x-1 transition-transform" />
            </button>
            <div>
                <h1 class="text-4xl font-display font-black text-white tracking-tight">Paramètres <span class="text-gold-400">&</span> Abonnements</h1>
                <p class="text-slate-400 mt-1 font-medium italic text-lg">Optimisez votre arsenal et gérez vos privilèges GoldArmy.</p>
            </div>
        </div>
        <div class="hidden lg:flex items-center gap-3 bg-indigo-500/10 border border-indigo-500/20 px-4 py-2 rounded-xl">
             <ShieldCheckIcon class="w-5 h-5 text-indigo-400" />
             <span class="text-sm font-bold text-indigo-300">Compte vérifié</span>
        </div>
    </div>

    <!-- Pricing Grid -->
    <div class="grid grid-cols-1 lg:grid-cols-3 gap-8 mb-16 relative">
      <!-- Background Glow decor -->
      <div class="absolute -top-24 left-1/2 -translate-x-1/2 w-[600px] h-[400px] bg-gold-500/5 blur-[100px] pointer-events-none"></div>

      <div 
        v-for="tier in displayTiers" 
        :key="tier.id"
        class="relative flex flex-col p-8 rounded-[2.5rem] border transition-all duration-500 group"
        :class="[
            tier.highlighted 
                ? 'bg-surface-900 border-gold-500 shadow-[0_0_40px_rgba(245,158,11,0.15)] ring-1 ring-gold-500/50 scale-105 z-10' 
                : 'bg-surface-900 border-surface-800 hover:border-surface-600'
        ]"
      >
        <!-- Popular Badge -->
        <div v-if="tier.highlighted" class="absolute -top-4 left-1/2 -translate-x-1/2 px-4 py-1.5 bg-gradient-to-r from-gold-500 to-amber-600 rounded-full text-[10px] font-black text-surface-950 uppercase tracking-widest shadow-lg shadow-gold-500/30">
            Le plus populaire
        </div>

        <div class="mb-8">
            <div 
                class="w-14 h-14 rounded-2xl flex items-center justify-center mb-6 bg-gradient-to-br transition-all duration-500 group-hover:scale-110"
                :class="tier.gradient"
            >
                <component :is="tier.icon" class="w-7 h-7" :class="tier.highlighted ? 'text-gold-400' : 'text-slate-400'" />
            </div>
            <h3 class="text-2xl font-display font-bold text-white mb-2">{{ tier.name }}</h3>
            <div class="flex items-baseline gap-1 mb-4">
                <span class="text-5xl font-black text-white tracking-tighter">{{ tier.price }}</span>
                <span class="text-slate-500 font-bold uppercase text-xs tracking-widest">/ mois</span>
            </div>
            <p class="text-slate-400 text-sm leading-relaxed font-medium">{{ tier.description }}</p>
        </div>

        <div class="flex-1 space-y-4 mb-10">
            <div v-for="feature in tier.features" :key="feature" class="flex items-start gap-3">
                <div class="mt-1 w-5 h-5 rounded-full bg-emerald-500/10 flex items-center justify-center shrink-0 border border-emerald-500/20">
                    <CheckIcon class="w-3 h-3 text-emerald-400" />
                </div>
                <span class="text-sm font-semibold text-slate-300">{{ feature }}</span>
            </div>
            <div v-for="unfeat in tier.unavailable" :key="unfeat" class="flex items-start gap-3 opacity-30 grayscale">
                <div class="mt-1 w-5 h-5 rounded-full bg-slate-800 flex items-center justify-center shrink-0 border border-slate-700">
                    <div class="w-1.5 h-px bg-slate-500"></div>
                </div>
                <span class="text-sm font-semibold text-slate-500 line-through">{{ unfeat }}</span>
            </div>
        </div>

        <button 
            @click="handleSubscribe(tier.id)"
            :disabled="isSubscribing"
            class="w-full py-4 rounded-2xl font-black text-sm uppercase tracking-widest transition-all duration-300 active:scale-95 disabled:opacity-50"
            :class="[
                tier.highlighted
                    ? 'bg-gradient-to-r from-gold-500 to-amber-600 text-surface-950 shadow-lg shadow-gold-500/20 hover:shadow-gold-500/40'
                    : 'bg-surface-800 border border-surface-700 text-white hover:bg-surface-700 hover:border-slate-500'
            ]"
        >
            <span v-if="isSubscribing && !((tier.id === 'tier-free' && userTier === 'FREE') || 
                   (tier.id === 'tier-essential' && userTier === 'ESSENTIAL') ||
                   (tier.id === 'tier-pro' && userTier === 'PRO'))" class="flex items-center justify-center gap-2">
                <svg class="animate-spin h-4 w-4 text-current" fill="none" viewBox="0 0 24 24"><circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle><path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path></svg>
                Chargement...
            </span>
            <span v-else>{{ tier.buttonText }}</span>
        </button>
      </div>
    </div>

    <!-- Extra Settings Section -->
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-20 animate-fade-in-up" style="animation-delay: 200ms">
        <div class="bg-surface-900 border border-surface-800 rounded-[2rem] p-8 hover:border-surface-700 transition-colors">
            <div class="flex items-center gap-4 mb-6">
                <div class="p-3 bg-indigo-500/10 rounded-xl">
                    <SparklesIcon class="w-6 h-6 text-indigo-400" />
                </div>
                <h4 class="text-xl font-display font-bold text-white">Préférences IA</h4>
            </div>
            <div class="space-y-6">
                <div class="flex items-center justify-between">
                    <div>
                        <p class="text-white font-bold text-sm">Précision de filtrage Sniper</p>
                        <p class="text-xs text-slate-500">Définit le niveau de sévérité de Gemini 3.1</p>
                    </div>
                    <select class="bg-surface-800 border border-surface-700 text-white text-xs font-bold rounded-lg px-3 py-1.5 focus:outline-none focus:ring-1 focus:ring-gold-500">
                        <option>Chirurgicale</option>
                        <option selected>Standard (Auto)</option>
                        <option>Large</option>
                    </select>
                </div>
                <div class="flex items-center justify-between">
                    <div>
                        <p class="text-white font-bold text-sm">Voix de l'entretien</p>
                        <p class="text-xs text-slate-500">Sélectionnez le profil vocal du recruteur IA</p>
                    </div>
                    <select class="bg-surface-800 border border-surface-700 text-white text-xs font-bold rounded-lg px-3 py-1.5 focus:outline-none focus:ring-1 focus:ring-gold-500">
                        <option>Directeur RH (Formel)</option>
                        <option>Tech Lead (Direct)</option>
                        <option selected>Recruteur Standard</option>
                    </select>
                </div>
            </div>
        </div>

        <div class="bg-surface-900 border border-surface-800 rounded-[2rem] p-8 hover:border-surface-700 transition-colors">
            <div class="flex items-center gap-4 mb-6">
                <div class="p-3 bg-emerald-500/10 rounded-xl">
                    <UserGroupIcon class="w-6 h-6 text-emerald-400" />
                </div>
                <h4 class="text-xl font-display font-bold text-white">Profil & Confidentialité</h4>
            </div>
            <div class="space-y-4">
                <div class="p-4 bg-surface-950 border border-surface-800 rounded-2xl flex items-center justify-between">
                    <div class="flex items-center gap-3">
                        <div class="w-10 h-10 rounded-full bg-gold-500/10 flex items-center justify-center text-gold-400 font-bold">Y</div>
                        <div>
                            <p class="text-sm font-bold text-white">Yves D.</p>
                            <p class="text-[10px] text-slate-500 uppercase font-black">Utilisateur GoldArmy</p>
                        </div>
                    </div>
                    <button class="text-xs font-bold text-slate-400 hover:text-white transition-colors">Modifier</button>
                </div>
                <button class="w-full text-center py-3 border border-surface-800 hover:bg-rose-500/5 hover:border-rose-500/20 text-slate-500 hover:text-rose-400 rounded-2xl text-xs font-bold transition-all">
                    Supprimer mon compte et mes données
                </button>
            </div>
        </div>
    </div>
  </div>
</template>

<style scoped>
.animate-fade-in-up {
  animation: fadeInUp 0.6s ease-out forwards;
}

@keyframes fadeInUp {
  from {
    opacity: 0;
    transform: translateY(20px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}
</style>
